version: '3.1'

services:
  app:
    build: ./
    ports:
      - 8080:8080
    links:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=2008
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2008

  adminer:
    image: adminer
    restart: always
    ports:
      - 8081:8080